using gpg instead of openssl for aes-encrypt and aes-decrypt

diff --git a/scripts/aes-encrypt b/scripts/aes-encrypt
--- a/scripts/aes-encrypt
+++ b/scripts/aes-encrypt
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+if [ -t 1 ]; then
+	echo "ERROR: will not output encrypted data to a terminal (it would be ugly and useless"
+	exit 1
+fi
+
+#gpg --s2k-mode 3 --s2k-count 65011712 --s2k-digest-algo SHA512 --s2k-cipher-algo AES256
+gpg --symmetric --cipher-algo AES256 -
+exit $?
+
+# this is the old script, which has been broken due to openssl:
+
 VERSION=$(openssl version | awk '{print $2}')
 VERSION_MAJOR=$(echo $VERSION | tr '.' ' ' | awk '{print $1}')
 VERSION_MINOR=$(echo $VERSION | tr '.' ' ' | awk '{print $2}')
