updated extract-cc

diff --git a/scripts/extract-cc b/scripts/extract-cc
--- a/scripts/extract-cc
+++ b/scripts/extract-cc
@@ -1,7 +1,15 @@
-#!/bin/bash
+	#!/bin/bash
 
 SRCFILE="$1"
-if [ -z "$(ffprobe \"$SRCFILE\" | grep \"Closed Captions\")" ]; then
+if [ -z "$SRCFILE" ]; then
+	echo "ERROR: must specify input file"
+	exit 1
+fi
+if [ ! -e "$SRCFILE" ]; then
+	echo "ERROR: $SRCFILE not found"
+	exit 1
+fi
+if [ -z "$(ffprobe $SRCFILE |& grep 'Closed Captions')" ]; then
 	echo "ERROR: $SRCFILE doesn't appear to have closed captions."
 	exit 1
 fi
