modified make-hosts because I moved

diff --git a/scripts/make-hosts b/scripts/make-hosts
--- a/scripts/make-hosts
+++ b/scripts/make-hosts
@@ -83,11 +83,11 @@ else
 			echo "ERROR: unable to fetch subnet information"
 			exit 1
 		fi
-		curl http://vpn.bismith.net/subnets/apt.txt 2> /dev/null >> $tempfile
-		if [ "$?" -ne "0" ]; then
-			echo "ERROR: unable to fetch subnet information"
-			exit 1
-		fi
+		#curl http://vpn.bismith.net/subnets/apt.txt 2> /dev/null >> $tempfile
+		#if [ "$?" -ne "0" ]; then
+		#	echo "ERROR: unable to fetch subnet information"
+		#	exit 1
+		#fi
 		curl http://vpn.bismith.net/subnets/home.txt 2> /dev/null >> $tempfile
 		if [ "$?" -ne "0" ]; then
 			echo "ERROR: unable to fetch subnet information"
