fixed tarpv

diff --git a/scripts/tarpv b/scripts/tarpv
--- a/scripts/tarpv
+++ b/scripts/tarpv
@@ -1,22 +1,10 @@
 #!/bin/bash
 
-# Use -gt 1 to consume two arguments per pass in the loop (e.g. each
-# argument has a corresponding value to go with it).
-# Use -gt 0 to consume one or more arguments per pass in the loop (e.g.
-# some arguments don't have a corresponding value to go with it such
-# as in the --default example).
-# note: if this is set to -gt 0 the /etc/hosts part is not recognized ( may be a bug )
+SIZE=$(du -bd 0 $@ | awk '{s += $1} END {printf "%.0f", s}')
 
-TOTALSIZE=0
-ALLARGS="$@"
-
-while [[ $# -gt 0 ]]; do
-	key="$1"
-	if [ -e "./$1" ]; then
-		VALUE=$(du -bd 0 "./$1" | awk '{print $1}')
-		TOTALSIZE=$(expr $TOTALSIZE + $VALUE)
-	fi
-	shift # past argument or value
-done
-
-tar $ALLARGS | pv -s $TOTALSIZE
+if [ ! -t 1 ]; then
+	tar -c $@ | pv -s $SIZE
+else
+	echo "ERROR: cannot output to a terminal"
+	exit 1
+fi
